#!/usr/bin/env python3
"""Regenerate ``api_routes.py`` from the NestJS controllers in ``backend/src``.

``api_routes.py`` is the route inventory that ``test_api_surface.py`` walks in
order to touch every endpoint the backend exposes. Keeping the inventory
generated (instead of hand-typed) means a new controller route cannot silently
escape the surface tests.

Run this whenever a controller changes::

    python generate_api_routes.py

The parser is deliberately small:

* every ``export class`` in a ``*.controller.ts`` file is treated as one
  controller with the prefix of its own ``@Controller(...)`` decorator;
* a route is ``auth_required`` when either the controller class or the method
  carries a ``@UseGuards(...)`` decorator;
* anything that is not ``GET`` is considered ``mutating`` so the tests can skip
  it unless writes have been explicitly enabled.
"""

from __future__ import annotations

import pathlib
import re

HERE = pathlib.Path(__file__).resolve().parent          # backend/tests/api-tests
BACKEND_SRC = HERE.parents[1] / "src"                   # backend/src
OUTPUT = HERE / "api_routes.py"

CONTROLLER_RE = re.compile(r"@Controller\(\s*(?:'([^']*)')?\s*\)")
GUARD_RE = re.compile(r"@UseGuards\(")
ROUTE_RE = re.compile(r"@(Get|Post|Put|Patch|Delete)\(\s*(?:'([^']*)')?\s*\)")

HEADER = '''"""Route inventory for the OpenRx backend API.

AUTO-GENERATED by ``generate_api_routes.py`` — do not edit by hand.

Each entry describes one endpoint declared by a NestJS controller:

* ``method``        — HTTP verb (``GET``, ``POST``, ``PUT``, ``PATCH``, ``DELETE``)
* ``path``          — path relative to the API prefix (``/api``), e.g. ``/patients``
* ``auth_required`` — the controller class or the route method is guarded
* ``controller``    — source file, for traceability
"""

from __future__ import annotations

from typing import NamedTuple


class Route(NamedTuple):
    """One HTTP endpoint exposed by the backend."""

    method: str
    path: str
    auth_required: bool
    controller: str


API_ROUTES: tuple[Route, ...] = (
'''


def parse_controller(path: pathlib.Path) -> list[tuple[str, str, bool]]:
    """Return ``(method, path, auth_required)`` tuples for one controller file.

    The text is sliced at every ``@Controller(...)`` decorator, so a controller
    segment ends *before* the next controller's decorators. That boundary is
    what keeps the last route of a public controller from inheriting the guards
    declared on the controller that follows it.
    """
    text = path.read_text(encoding="utf-8", errors="ignore")
    anchors = list(CONTROLLER_RE.finditer(text))
    routes: list[tuple[str, str, bool]] = []

    for index, anchor in enumerate(anchors):
        end = anchors[index + 1].start() if index + 1 < len(anchors) else len(text)
        segment = text[anchor.start() : end]
        prefix = anchor.group(1) or ""

        found = list(ROUTE_RE.finditer(segment))
        first_route = found[0].start() if found else len(segment)
        # Class decorators sit above the first route; method decorators below it.
        class_guard = GUARD_RE.search(segment[:first_route]) is not None

        for position, match in enumerate(found):
            method = match.group(1).upper()
            route_path = match.group(2) or ""
            window_end = (
                found[position + 1].start()
                if position + 1 < len(found)
                else len(segment)
            )
            method_guard = GUARD_RE.search(segment[match.end() : window_end]) is not None

            full_path = "/" + "/".join(part for part in (prefix, route_path) if part)
            routes.append((method, full_path, class_guard or method_guard))

    return routes


def build() -> list[tuple[str, str, bool, str]]:
    """Collect and de-duplicate the route inventory from the backend source."""
    rows: list[tuple[str, str, bool, str]] = []
    for path in sorted(BACKEND_SRC.glob("**/*.controller.ts")):
        relative = path.relative_to(BACKEND_SRC.parent).as_posix()
        for method, route_path, guarded in parse_controller(path):
            rows.append((method, route_path, guarded, relative))

    # Stable, human-friendly ordering; de-duplicate identical entries.
    return sorted(set(rows), key=lambda row: (row[1], row[0], row[3]))


def render(rows: list[tuple[str, str, bool, str]]) -> str:
    """Render the inventory as the contents of ``api_routes.py``."""
    lines = [HEADER]
    for method, route_path, guarded, controller in rows:
        lines.append(
            f'    Route("{method}", "{route_path}",{"" if guarded else " "}'
            f'{"True" if guarded else "False"}, "{controller}"),\n'
        )
    lines.append(")\n")
    return "".join(lines)


def main() -> None:
    rows = build()
    OUTPUT.write_text(render(rows), encoding="utf-8")
    guarded = sum(1 for row in rows if row[2])
    print(
        f"Wrote {len(rows)} routes to {OUTPUT.name} "
        f"({guarded} guarded, {len(rows) - guarded} public)"
    )


if __name__ == "__main__":
    main()
